In [8]:
import pandas as pd
import ast
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


df = pd.read_csv(
    "gutenberg_books.csv",
    dtype={"book_id": str}
)

df["tokens"] = df["tokens_clean"].apply(ast.literal_eval)

df["texto_tfidf"] = df["tokens"].apply(
    lambda tokens: " ".join(tokens)
)

In [10]:
for i in range(3):
    print("=" * 80)
    print(f"BOOK ID: {df.loc[i, 'book_id']}")
    print()
    print(df.loc[i, "tokens_clean"])

================================================================================
BOOK ID: 71


In [11]:
vectorizer = TfidfVectorizer()

X_tfidf = vectorizer.fit_transform(df["texto_tfidf"])

print("Dimensão da matriz TF-IDF:", X_tfidf.shape)

# transformar os textos em uma matriz de pesos TF-IDF
# resultando em uma matriz com dimensões de 312 linhas (livros) por 17.336 colunas
# (termos/palavras únicas).

Dimensão da matriz TF-IDF: (312, 115899)

In [12]:
def buscar(consulta, quantidade=10):
    consulta_tfidf = vectorizer.transform([consulta])

    similaridades = cosine_similarity(
        consulta_tfidf,
        X_tfidf
    ).flatten()

    indices = similaridades.argsort()[::-1]

    resultados = df.iloc[indices[:quantidade]].copy()
    resultados["similaridade"] = similaridades[indices[:quantidade]]

    return resultados

In [13]:
resultados = buscar(
    "war politics",
    quantidade=20
)

resultados[
    ["book_id", "similaridade"]
]

    book_id  similaridade
105    1804      0.207634
146    1946      0.152072
8      1484      0.055448
302    1713      0.052640
58     1143      0.052598
39      536      0.048498
279    2464      0.042292
158    1477      0.040220
129    1821      0.036768
54     2026      0.036450
83      847      0.035521
233    2130      0.034677
133     816      0.029057
99      245      0.028719
159    2308      0.028242
204     374      0.026111
40      623      0.026000
303    2231      0.025972
34     2595      0.024413
251     712      0.024171

In [14]:
resultados = buscar(
    "religion morality",
    quantidade=20
)

resultados[
    ["book_id", "similaridade"]
]

    book_id  similaridade
81     2051      0.057179
286    1689      0.048738
248     333      0.048357
77     2330      0.041275
130    1885      0.039538
276    1335      0.037711
86      908      0.036592
233    2130      0.034347
206     921      0.033391
98      608      0.030660
40      623      0.030385
202    2445      0.029226
133     816      0.026752
35     1436      0.024421
282    2373      0.023370
259    1395      0.022903
11     1886      0.022439
47     1360      0.021179
61     2133      0.021164
58     1143      0.016875